@startuml classDiagram
Title Class Diagram for dnd module

class Dice {
  -dice: Array[int]
  +roll(quantity: int, sides: int): array[int]
}

Interface offensive {
  +attack(): int
}

Interface defensive {
  +defend(): int
}

abstract class Character {
  -name: string
  -maxHitPoints: int
  -currentHitPoints: int
  +getName(): string
  +getMaxHitPoints(): int
  +getCurrentHitPoints(): int
  -setName(name: string): void
  -setMaxHitPoints(maxHitPoints: int, currentHitPoints: int): void
  -setCurrentHitPoints(currentHitPoints: int): void
  +attack(target: Character, dice: Dice): int
}

class Player extends Character {

}

class Enemy extends Character {

}

class Npc extends Character {

}


Character --> Dice : rolls


@enduml