@startuml classDiagram
Title Class Diagram fight module

class Dice {
  +rollDice(quantity: int, sides: int): int[]
}

class Offensive {
  +checkIfHit(): boolean
  +calculateDamage(damage: int[]): int
}

class Defensive {
  +calculateDamageTaken(damage: int, armorClass: int): int
}

abstract class Character {
  -name: string
  -maxHitPoints: int
  -currentHitPoints: int
  -attackPower: int
  -numberOfAttacks: int
  -speed: int
  -armorClass: int
  -healAmount: int
  +Character(name: string, attackPower: int, startHpNumberOfDice: int, startHpSidesPerDie: int)
  +getName(): string
  +getMaxHitPoints(): int
  +getCurrentHitPoints(): int
  +getAttackPower(): int
  +getArmorClass(): int
  +getSpeed(): int
  +getIsAlive(): boolean
  +attack(target: Character): void
  +defend(damage: int): void
  +guard(): void
  +heal(targetToHeal: Character): void
  -setName(name: string): void
  -setInitialHitPoints(numberOfDice: int, sidesPerDie: int): void
  -takeDamage(damage: int): void
}

class Player {
  +Player(name: string, attackPower: int)
}

class Enemy {
  +Enemy(name: string, attackPower: int)
}

class PlayerFightActions <<union type>> {
  = "attack" (target: Enemy)
  = "guard"
  = "heal" (target: Player)
  = "skipTurn"
}

class ChoosePlayerAction <<function type>> {
  +(_player: Player, _livingAllies: Player[], _livingOpponents: Enemy[]): PlayerFightActions
}

class FightEncounterHandler {
  -playerFighters: Player[]
  -enemyFighters: Enemy[]
  -fightParticipants: Character[]
  +FightEncounterHandler(playerFighters: Player[], enemyFighters: Enemy[])
  +getFightMembers(): readonly Character[]
  +getLivingAllies(currentCharacter: Character): Character[]
  +getLivingOpponents(currentCharacter: Character): Character[]
  +setupFight(): void
  +startFight(choosePlayerAction: ChoosePlayerAction): void
  -setFightOrder(): void
  -startTurn(choosePlayerAction: ChoosePlayerAction): void
  -handlePlayerTurn(player: Player, choosePlayerAction: ChoosePlayerAction): void
  -executePlayerAction(player: Player, action: PlayerFightActions): void
  -handleEnemyTurn(enemy: Enemy): void
  -shouldFightContinue(): boolean
}

Player --|> Character
Enemy --|> Character
Character ..> Dice : rolls for behavior actions
Character ..> Offensive : calculates offensive behavior
Character ..> Defensive : calculates defensive behavior
FightEncounterHandler "1" o-- "..*" Player : playerFighters
FightEncounterHandler "1" o-- "..*" Enemy : enemyFighters
FightEncounterHandler ..> Character : sets order of participants
FightEncounterHandler ..> ChoosePlayerAction : requests player action
ChoosePlayerAction ..> PlayerFightActions : handles player action input
PlayerFightActions ..> Player : Performs defensive actions
PlayerFightActions ..> Enemy : performs offensive actions

@enduml




