@startuml systemDiagramDice
Title System Diagram for Dice Rolling

actor User
participant DiceSystem

User --> DiceSystem : Roll Dice
activate DiceSystem
DiceSystem --> User : Return Dice Result
deactivate DiceSystem


@enduml
